openapi: "3.0.0"
info:
  title: Office Health - API
  version: 0.0.1
paths:
  /quote:
    get:
      summary: Retrieve quotes
      operationId: quote
      tags:
        - quote
      parameters:
        - name: tag
          in: query
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Quote"
        default:
          description: Unexpected error
  /tag:
    get:
      summary: Retrieve tag tree
      operationId: tag
      tags:
        - tag
      responses:
        '200':
          description: Successful operation
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Tag"
        default:
          description: Unexpected error
components:
  schemas:
    Quote:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        author:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    Tag:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        parentTag:
            $ref: '#/components/schemas/Tag'
        childTags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'