openapi: "3.0.0"
info:
  title: Office Health - API
  version: 0.0.1
paths:
  /quote:
    get:
      summary: Retrieve quotes
      operationId: quote
      tags:
        - quote
      parameters:
        - name: tag
          in: query
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Quote"
        default:
          description: Unexpected error
  /quote/tag:
    get:
      summary: Retrieve quotes tags
      operationId: quoteTag
      tags:
        - quoteTag
      responses:
        '200':
          description: Successful operation
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/QuoteTag"
        default:
          description: Unexpected error
  /workout:
    get:
      summary: Generate and receive random workout
      operationId: workout
      tags:
        - workout
      parameters:
        - name: time
          in: query
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Workout'
        default:
          description: Unexpected error
components:
  schemas:
    Workout:
      type: object
      required:
        - exercises
      properties:
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/WorkoutExercise'
    WorkoutExercise:
      type: object
      required:
        - exercise
        - time
      properties:
        exercise:
          $ref:
            '#/components/schemas/Exercise'
        time:
          type: integer
          format: int64
    Exercise:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
    Quote:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        author:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/QuoteTag'
    QuoteTag:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string